# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_1',
            old_name='dur',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='post_1',
            old_name='mail',
            new_name='email',
        ),
    ]
